# Generated by Django 6.0.3 on 2026-04-15 08:14

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sd_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availablemodel",
            name="api_key",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                help_text="API key for this model's provider (encrypted at rest).",
                max_length=500,
            ),
        ),
    ]
