# Generated by Django 5.2.14 on 2026-05-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sd_models", "0006_extend_model_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablemodel",
            name="cost_per_audio_minute",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="USD per minute of audio (for transcription / STT models). Manually set.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
