# Generated by Django 6.1 on 2026-09-29 22:05

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sd_models", "0007_availablemodel_cost_per_audio_minute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availablemodel",
            name="cache_read_cost_per_mtok",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Price of a prompt token read from the provider's cache (USD per Mtok). Blank = charged at the input rate, which overstates cache-heavy use.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="availablemodel",
            name="cache_write_cost_per_mtok",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Price of writing a prompt token to the cache (USD per Mtok). Blank = input rate.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="LLMCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "root_name",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("slot", models.CharField(blank=True, max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("embedding", "Embedding"),
                            ("transcription", "Transcription"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=200)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("base_url_host", models.CharField(blank=True, max_length=200)),
                ("data_residency", models.CharField(blank=True, max_length=10)),
                (
                    "input_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "output_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "cache_read_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "cache_write_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("price_source", models.CharField(blank=True, max_length=20)),
                (
                    "input_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="All input, cached included."
                    ),
                ),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "reasoning_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="A subset of output."
                    ),
                ),
                ("audio_seconds", models.FloatField(blank=True, null=True)),
                (
                    "input_cost",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=14, null=True
                    ),
                ),
                (
                    "output_cost",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=14, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("input_cost"), "+", models.F("output_cost")
                        ),
                        output_field=models.DecimalField(
                            decimal_places=8, max_digits=14, null=True
                        ),
                    ),
                ),
                (
                    "cache_hit",
                    models.BooleanField(
                        default=False, help_text="Served from struckdown's cache."
                    ),
                ),
                ("ok", models.BooleanField(default=True)),
                ("error_class", models.CharField(blank=True, max_length=120)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("finish_reason", models.CharField(blank=True, max_length=40)),
                (
                    "available_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="A link for filtering. The columns on this row are the record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="sd_models.availablemodel",
                    ),
                ),
            ],
            options={
                "db_table": "llm_call",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMCallPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payload",
                        to="sd_models.llmcall",
                    ),
                ),
            ],
            options={
                "db_table": "llm_call_payload",
            },
        ),
        migrations.CreateModel(
            name="LLMSpan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="What this span is: 'http:tower:module_detail', 'celery:hub_tagging.autotag', 'hub_assistant.turn'.",
                        max_length=160,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=64)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("capture_payloads", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="sd_models.llmspan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_spans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "llm_span",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="llmcall",
            name="span",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calls",
                to="sd_models.llmspan",
            ),
        ),
        migrations.AddIndex(
            model_name="llmspan",
            index=models.Index(
                fields=["name", "started_at"], name="llm_span_name_fdc661_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmcall",
            index=models.Index(
                fields=["span", "created_at"], name="llm_call_span_id_ca629f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmcall",
            index=models.Index(
                fields=["root_name", "created_at"], name="llm_call_root_na_3b30ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="llmcall",
            index=models.Index(
                fields=["kind", "created_at"], name="llm_call_kind_da9b62_idx"
            ),
        ),
    ]
