# Generated by Django 6.1 on 2026-09-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sd_models", "0008_usage_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMCosts",
            fields=[],
            options={
                "verbose_name": "LLM costs",
                "verbose_name_plural": "LLM costs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sd_models.llmcall",),
        ),
    ]
